export const ACCESS_CHAT_REQUEST='ACCESS_CHAT_REQUEST'
export const ACCESS_CHAT_SUCCESS='ACCESS_CHAT_SUCCESS'
export const ACCESS_CHAT_FAIL='ACCESS_CHAT_FAIL'
export const ACCESS_CHAT_RESET='ACCESS_CHAT_RESET'

export const FETCH_CHAT_REQUEST='FETCH_CHAT_REQUEST'
export const FETCH_CHAT_SUCCESS='FETCH_CHAT_SUCCESS'
export const FETCH_CHAT_FAIL='FETCH_CHAT_FAIL'
export const FETCH_CHAT_RESET='FETCH_CHAT_RESET'

export const CREATE_GROUP_REQUEST='CREATE_GROUP_REQUEST'
export const CREATE_GROUP_SUCCESS='CREATE_GROUP_SUCCESS'
export const CREATE_GROUP_FAIL='CREATE_GROUP_FAIL'
export const CREATE_GROUP_RESET='CREATE_GROUP_RESET'

export const UPDATE_GROUP_REQUEST='UPDATE_GROUP_REQUEST'
export const UPDATE_GROUP_SUCCESS='UPDATE_GROUP_SUCCESS'
export const UPDATE_GROUP_FAIL='UPDATE_GROUP_FAIL'
export const UPDATE_GROUP_RESET='UPDATE_GROUP_RESET'

export const REMOVEFROM_GROUP_REQUEST='REMOVEFROM_GROUP_REQUEST'
export const REMOVEFROM_GROUP_SUCCESS='REMOVEFROM_GROUP_SUCCESS'
export const REMOVEFROM_GROUP_FAIL='REMOVEFROM_GROUP_FAIL'
export const REMOVEFROM_GROUP_RESET='REMOVEFROM_GROUP_RESET'
