export const MESSAGES_SEND_REQUEST='MESSAGES_SEND_REQUEST'
export const MESSAGES_SEND_SUCCESS='MESSAGES_SEND_SUCCESS'
export const MESSAGES_SEND_FAIL='MESSAGES_SEND_FAIL'
export const MESSAGES_SEND_RESET='MESSAGES_SEND_RESET'

export const MESSAGES_ALL_REQUEST='MESSAGES_ALL_REQUEST'
export const MESSAGES_ALL_SUCCESS='MESSAGES_ALL_SUCCESS'
export const MESSAGES_ALL_FAIL='MESSAGES_ALL_FAIL'
export const MESSAGES_ALL_RESET='MESSAGES_ALL_RESET'